# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ns2\Desktop\design.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WhatsappAutomation(object):
    def setupUi(self, WhatsappAutomation):
        WhatsappAutomation.setObjectName("MainWindow")
        WhatsappAutomation.resize(800, 596)
        WhatsappAutomation.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WhatsappAutomation.setWindowIcon(icon)
        WhatsappAutomation.setAutoFillBackground(False)
        WhatsappAutomation.setStyleSheet("background:url(back.png);")
        self.centralwidget = QtWidgets.QWidget(WhatsappAutomation)
        self.centralwidget.setObjectName("centralwidget")
        self.contact_type = QtWidgets.QLabel(self.centralwidget)
        self.contact_type.setGeometry(QtCore.QRect(40, 20, 81, 21))
        self.contact_type.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contact_type.setFont(font)
        self.contact_type.setAcceptDrops(False)
        self.contact_type.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contact_type.setTextFormat(QtCore.Qt.RichText)
        self.contact_type.setObjectName("contact_type")
        self.unsaved = QtWidgets.QRadioButton(self.centralwidget)
        self.unsaved.setGeometry(QtCore.QRect(160, 20, 82, 17))
        self.unsaved.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.unsaved.setFont(font)
        self.unsaved.setObjectName("unsaved")
        self.saved = QtWidgets.QRadioButton(self.centralwidget)
        self.saved.setGeometry(QtCore.QRect(250, 20, 82, 17))
        self.saved.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.saved.setFont(font)
        self.saved.setObjectName("saved")
        self.contact_file = QtWidgets.QLabel(self.centralwidget)
        self.contact_file.setGeometry(QtCore.QRect(40, 60, 111, 16))
        self.contact_file.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contact_file.setFont(font)
        self.contact_file.setObjectName("contact_file")
        self.selectfilebutton = QtWidgets.QToolButton(self.centralwidget)
        self.selectfilebutton.setGeometry(QtCore.QRect(160, 60, 141, 19))
        self.selectfilebutton.setStyleSheet("color:white")
        self.selectfilebutton.setObjectName("selectfilebutton")
        self.messagelabel = QtWidgets.QLabel(self.centralwidget)
        self.messagelabel.setGeometry(QtCore.QRect(40, 100, 111, 16))
        self.messagelabel.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.messagelabel.setFont(font)
        self.messagelabel.setObjectName("messagelabel")
        #self.messagebox = QtWidgets.QTextEdit(self.centralwidget)
        self.messagebox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.messagebox.setGeometry(QtCore.QRect(160, 100, 271, 141))
        self.messagebox.setStyleSheet("background:white")
        self.messagebox.setObjectName("messagebox")
        self.addmedia = QtWidgets.QPushButton(self.centralwidget)
        self.addmedia.setGeometry(QtCore.QRect(160, 250, 41, 23))
        self.addmedia.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addmedia.setFont(font)
        self.addmedia.setObjectName("addmedia")
        self.medialabel = QtWidgets.QLabel(self.centralwidget)
        self.medialabel.setGeometry(QtCore.QRect(210, 250, 100, 30))
        self.medialabel.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.medialabel.setFont(font)
        self.medialabel.setObjectName("medialabel")
        self.adddoc = QtWidgets.QPushButton(self.centralwidget)
        self.adddoc.setGeometry(QtCore.QRect(160, 280, 41, 23))
        self.adddoc.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.adddoc.setFont(font)
        self.adddoc.setObjectName("adddoc")
        self.doclabel = QtWidgets.QLabel(self.centralwidget)
        self.doclabel.setGeometry(QtCore.QRect(210, 280, 91, 21))
        self.doclabel.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.doclabel.setFont(font)
        self.doclabel.setObjectName("doclabel")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(260, 320, 75, 23))
        self.send.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.send.setFont(font)
        self.send.setObjectName("send")
        self.contactsuploaded = QtWidgets.QLabel(self.centralwidget)
        self.contactsuploaded.setGeometry(QtCore.QRect(540, 30, 161, 20))
        self.contactsuploaded.setStyleSheet("background:none;color:white")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contactsuploaded.setFont(font)
        self.contactsuploaded.setObjectName("contactsuploaded")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(530, 60, 181, 241))
        self.listWidget.setStyleSheet("background:white")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.radiovalue = QtWidgets.QLineEdit(self.centralwidget)
        self.radiovalue.setGeometry(QtCore.QRect(310, 20, 16, 16))
        self.radiovalue.setObjectName("radiovalue")
        self.radiovalue.hide()
        WhatsappAutomation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WhatsappAutomation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        WhatsappAutomation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WhatsappAutomation)
        self.statusbar.setObjectName("statusbar")
        WhatsappAutomation.setStatusBar(self.statusbar)

        self.retranslateUi(WhatsappAutomation)
        QtCore.QMetaObject.connectSlotsByName(WhatsappAutomation)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("WhatsappAutomation", "WhatsappAutomation"))
        self.contact_type.setText(_translate("WhatsappAutomation", "Contact Type :"))
        self.unsaved.setText(_translate("WhatsappAutomation", "UnSaved"))
        self.saved.setText(_translate("WhatsappAutomation", "Saved"))
        self.contact_file.setText(_translate("WhatsappAutomation", "Select Contact File:"))
        self.selectfilebutton.setText(_translate("WhatsappAutomation", "Browse ..."))
        self.messagelabel.setText(_translate("WhatsappAutomation", "Messege to Send:"))
        self.addmedia.setText(_translate("WhatsappAutomation", "+"))
        self.medialabel.setText(_translate("WhatsappAutomation", ": Add Media"))
        self.adddoc.setText(_translate("WhatsappAutomation", "+"))
        self.doclabel.setText(_translate("WhatsappAutomation", ": Add Document"))
        self.send.setText(_translate("WhatsappAutomation", "SEND"))
        self.contactsuploaded.setText(_translate("WhatsappAutomation", "Contacts Uploaded"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WhatsappAutomation = QtWidgets.QMainWindow()
    ui = Ui_WhatsappAutomation()
    ui.setupUi(WhatsappAutomation)
    WhatsappAutomation.show()
    sys.exit(app.exec_())

